site_name: JSON & YAML Messages for Yii
site_description: JSON and YAML message sources for Yii, high-performance PHP framework.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/yii2-json-messages

docs_dir: .
site_dir: ../web

repo_name: GitHub
repo_url: https://github.com/cedx/yii2-json-messages
edit_uri: ''

copyright: Copyright &copy; 2014 - 2019 Cédric Belin
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

extra:
  social:
  - {type: globe, link: 'https://belin.io'}
  - {type: github, link: 'https://github.com/cedx'}
  - {type: twitter, link: 'https://twitter.com/cedxbelin'}
  - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
- admonition
- codehilite

nav:
- Overview: index.md
- Installation: installation.md
- Usage: usage.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: blue grey, accent: light blue}
